-- =====================================================================
-- 0116 — schema `produto`: as 84 tabelas do QB Digital OS, isoladas
-- ---------------------------------------------------------------------
-- PORQUE UM SCHEMA À PARTE, E NÃO `public`
--
-- Há colisão de nomes reais com o que já existe em `public`: aprovacoes,
-- cobrancas, contactos, e — mais grave — `profiles`, que aqui já é a
-- identidade da própria equipa/Sede. Misturar identidade de duas coisas
-- diferentes na mesma tabela é o tipo de confusão que dá acesso errado
-- sem ninguém perceber porquê.
--
-- Um schema novo (`produto`) resolve isto de vez: mesmo projecto Supabase,
-- mesma factura, mas uma zona da base de dados só deste produto — zero
-- hipótese de colisão, mesmo que os nomes se repitam.
--
-- AS DEFINIÇÕES SÃO EXTRAÍDAS DA BASE DE DADOS VIVA da Quente e Bom
-- (information_schema.columns), não escritas de memória. 84 tabelas é
-- demasiado para confiar em transcrição.
--
-- Falta expor o schema `produto` na API da Supabase (Project Settings →
-- API → Exposed schemas) — isso é um botão no painel, não uma linha de
-- SQL, e fica por sua conta depois de correr isto.
--
-- O QUE NÃO VEM COPIADO: as chaves estrangeiras ENTRE estas 84 tabelas
-- (ex.: colaborador_documentos → employees) não foram extraídas — só as
-- colunas e a chave primária de cada tabela. É a mesma situação que já
-- existe na Quente e Bom hoje: a app garante a integridade no código,
-- não o Postgres. Fica registado, não resolvido: numa fase seguinte
-- vale a pena decidir se compensa acrescentá-las aqui.
--
-- SEIS TIPOS À MEDIDA (canal, devolucao_causa, gravidade, nc_estado,
-- nivel, order_estado) EXISTEM NA ORIGEM E NÃO AQUI. A 1.ª tentativa
-- desta migração falhou logo na linha 235 — "type gravidade does not
-- exist" — porque tentou usar o NOME do tipo como se fosse um tipo
-- nativo do Postgres. As 13 colunas que os usam ficam como `text`: a
-- app já trata estes campos como strings, e recriar seis enums só para
-- isto não valia a fragilidade. Perde-se a validação ao nível da base
-- de dados — a mesma perda, pela mesma razão, das chaves estrangeiras.
-- =====================================================================

create schema if not exists produto;

create table if not exists produto.empresas (
  id         uuid primary key default gen_random_uuid(),
  nome       text not null,
  criada_em  timestamptz not null default now()
);

insert into produto.empresas (nome)
  select 'Quente e Bom Angola'
  where not exists (select 1 from produto.empresas where nome = 'Quente e Bom Angola');


create table if not exists produto.account_movements (
  id text,
  cliente_id text,
  tipo text not null,
  documento text,
  data date not null,
  vencimento date,
  valor numeric(16,2) default 0 not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.acoes_comerciais (
  id text,
  cliente_id text not null,
  cliente_nome text,
  tipo text default 'Contacto'::text not null,
  titulo text not null,
  data_prevista date,
  responsavel text,
  estado text default 'Aberta'::text not null,
  notas text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.agenda_comercial (
  id text,
  comercial text not null,
  cliente_id text,
  cliente_nome text not null,
  data date not null,
  tipo text default 'Visita'::text not null,
  estado text default 'Planeada'::text not null,
  objetivo text,
  resultado text,
  notas text,
  criado_por uuid,
  criado_por_nome text,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.alertas_estado (
  id text,
  primeira_vista date default CURRENT_DATE not null,
  dono text,
  dono_id text,
  assumido_em timestamptz,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.audit_log (
  id int8 generated by default as identity,
  utilizador uuid,
  acao text not null,
  entidade text not null,
  payload jsonb,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.ausencias (
  id text,
  employee_id text,
  colaborador text,
  tipo text default 'Falta Justificada'::text not null,
  data_inicio date not null,
  data_fim date not null,
  motivo text,
  justificada bool default true not null,
  autor text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.cambio_salarios (
  ano int4 not null,
  mes int4 not null,
  eur_akz numeric not null,
  atualizado_em timestamptz default now() not null,
  atualizado_por text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (ano, mes)
);

create table if not exists produto.cobrancas (
  id text,
  comercial text not null,
  cliente_id text,
  cliente_nome text not null,
  tipo text default 'Recibo'::text not null,
  valor numeric(18,2) default 0 not null,
  data date,
  data_prometida date,
  estado text default 'Pendente'::text not null,
  notas text,
  criado_por uuid,
  criado_por_nome text,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.colaborador_amortizacoes (
  id text,
  divida_id text not null,
  ano int4 not null,
  mes int4 not null,
  valor numeric not null,
  recibo_id text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.colaborador_avaliacoes_internas (
  id uuid default gen_random_uuid(),
  employee_id text not null,
  respostas jsonb default '{}'::jsonb not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.colaborador_dividas (
  id text,
  employee_id text not null,
  tipo text default 'emprestimo'::text not null,
  data date not null,
  capital numeric not null,
  n_prestacoes int4 default 1 not null,
  valor_prestacao numeric not null,
  estado text default 'activa'::text not null,
  motivo text,
  autor text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.colaborador_documentos (
  id text,
  employee_id text,
  tipo text not null,
  numero text,
  validade date,
  ficheiro_path text,
  notas text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.comissao_config (
  id text default 'default'::text,
  limiar_min numeric(6,4) default 0.75 not null,
  limiar_max numeric(6,4) default 1.10 not null,
  taxa_media numeric(6,4) default 0.01 not null,
  taxa_alta numeric(6,4) default 0.015 not null,
  taxa_diretor numeric(6,4) default 0.005 not null,
  diretor_geral text default 'Hugo Rodrigues'::text not null,
  diretor_comercial text default 'Paulo Vieira'::text not null,
  iva_pct numeric(6,4) default 0.14 not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.competencias (
  id text,
  nome text not null,
  tipo text default 'Técnica'::text not null,
  alvo int4 default 3 not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.complaints (
  id text,
  cliente text,
  canal text,
  tipologia text,
  gravidade text,
  estado text default 'Aberta'::text,
  data timestamptz default now(),
  sla_horas int4,
  resolvida_em timestamptz,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.contactos (
  id uuid default gen_random_uuid(),
  entidade_tipo text not null,
  entidade_id text not null,
  funcao text not null,
  nome text,
  telefone text,
  email text,
  origem text,
  criado_em timestamptz default now() not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.contratos_trabalho (
  id text,
  colaborador_id text,
  colaborador_nome text not null,
  funcao text,
  categoria_profissional text,
  tipo_contrato text default 'Sem termo'::text not null,
  data_inicio date,
  data_fim date,
  periodo_experimental_dias int4,
  vencimento_base numeric,
  subsidios text,
  horario text,
  local_trabalho text,
  dados_pessoais jsonb default '{}'::jsonb not null,
  estado text default 'Rascunho'::text not null,
  documento_url text,
  notas text,
  gerado_em timestamptz,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.corrective_actions (
  id text,
  nc_id text,
  descricao text,
  responsavel text,
  prazo date,
  concluida bool default false,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.customers (
  id text,
  nome text not null,
  canal text not null,
  nif text,
  comercial text,
  cidade text,
  ativo bool default true not null,
  bloqueado bool default false not null,
  ultima_compra date,
  divida_total numeric(16,2) default 0,
  divida_vencida numeric(16,2) default 0,
  limite_credito numeric(16,2) default 0,
  atualizado_em timestamptz default now() not null,
  morada_fiscal text,
  condicao_pagamento text,
  email_geral text,
  telefone_geral text,
  contactos jsonb default '[]'::jsonb not null,
  cadencia_dias int4,
  marcas_que_compra jsonb,
  saldo_phc numeric(16,2),
  vencido_phc numeric(16,2),
  a_vencer_phc numeric(16,2),
  saldo_phc_em timestamptz,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.devolucoes (
  id text,
  cliente_id text,
  canal text not null,
  produto text,
  marca text,
  quantidade int4 default 0,
  valor numeric(16,2) default 0,
  causa text not null,
  estado text default 'Registada'::text not null,
  comercial text,
  data date not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.disc_resultados (
  email text not null,
  nome text not null,
  departamento text,
  d int4 default 0 not null,
  i int4 default 0 not null,
  s int4 default 0 not null,
  c int4 default 0 not null,
  primario text,
  secundario text,
  atualizado_em timestamptz default now() not null,
  employee_id text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (email)
);

create table if not exists produto.documentos_cliente (
  id text,
  cliente_id text not null,
  tipo text default 'Outro'::text not null,
  numero text,
  data date,
  valor numeric,
  documento_url text,
  origem text default 'Manual'::text,
  notas text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.documentos_fatura (
  id text,
  fatura_numero text not null,
  cliente_id text,
  tipo text default 'Comprovativo de Entrega'::text not null,
  descricao text,
  data date,
  documento_url text,
  origem text default 'Manual'::text not null,
  criado_por text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.documentos_por_atribuir (
  id text,
  origem text not null,
  ficheiro text not null,
  tipo text not null,
  ficheiro_path text not null,
  palpite_id text,
  palpite_nome text,
  motivo text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.drivers (
  id text,
  nome text not null,
  carta text,
  validade_carta date,
  viatura text,
  telefone text,
  ativo bool default true not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.employees (
  id text,
  nome text not null,
  departamento text,
  funcao text,
  estado text default 'Activo'::text,
  admissao date,
  formacao_em_falta bool default false,
  disc_dominante text,
  atualizado_em timestamptz default now(),
  pica_ponto bool default true not null,
  ponto_id text,
  morada text,
  nif text,
  num_ss text,
  telefone text,
  email text,
  num_filhos int4 default 0 not null,
  iban text,
  banco text,
  eh_motorista bool default false not null,
  data_nascimento date,
  bi_numero text,
  categoria_profissional text,
  centro_custo text,
  turno_id text,
  exame_medico_data date,
  exame_aptidao text,
  cartao_sanidade_validade date,
  provincia text,
  municipio text,
  foto_path text,
  ficha_token text,
  dados_autopreenchidos_em timestamptz,
  ficha_codigo text,
  ficha_token_expira_em timestamptz,
  num_filhos_declarado int4,
  num_filhos_declarado_em timestamptz,
  auto_registado_em timestamptz,
  possivel_duplicado bool default false not null,
  departamento_declarado text,
  funcao_declarada text,
  funcao_dep_declarado_em timestamptz,
  nacionalidade text default 'Angolana'::text,
  phc_identidade text,
  comissao_origem text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.encomendas_dia (
  id text,
  obrano int4,
  cliente_id text,
  nome text,
  data date not null,
  fechada bool default false not null,
  valor numeric(18,2) default 0 not null,
  itens int4 default 0 not null,
  atualizado_em timestamptz default now() not null,
  custo numeric(18,2) default 0 not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.entregas (
  order_id text not null,
  entregue_em timestamptz default now() not null,
  entregue_por text,
  estado_entrega text,
  matricula text,
  motorista text,
  armazem text,
  satisfacao text,
  saida_paletes numeric,
  data_prevista date,
  data_entrega date,
  observacoes text,
  comercial text,
  fatura text,
  cliente text,
  valor numeric,
  data_encomenda date,
  atualizado_por text,
  atualizado_em timestamptz default now(),
  empresa_id uuid not null references produto.empresas(id),
  primary key (order_id)
);

create table if not exists produto.epi_items (
  id text,
  epi text,
  area text,
  entregues int4,
  necessarios int4,
  proxima_reposicao date,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.estabelecimentos (
  id text,
  cliente_id text not null,
  estab int4 not null,
  nome text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.extrato_partilhas (
  codigo text not null,
  cliente_id text not null,
  criado_por text,
  criado_em timestamptz default now() not null,
  expira_em timestamptz not null,
  ativo bool default true not null,
  acessos int4 default 0 not null,
  modo text default 'completo'::text not null,
  desde date,
  ate date,
  empresa_id uuid not null references produto.empresas(id),
  primary key (codigo)
);

create table if not exists produto.feriados (
  id uuid default gen_random_uuid(),
  data date not null,
  designacao text not null,
  ambito text default 'nacional'::text not null,
  municipio text,
  movel bool default false not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.ferias (
  id text,
  colaborador text not null,
  ano int4 not null,
  direito int4 default 22 not null,
  programadas int4 default 0 not null,
  gozadas int4 default 0 not null,
  notas text,
  atualizado_em timestamptz default now() not null,
  employee_id text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.ferias_periodos (
  id text,
  employee_id text,
  colaborador text not null,
  ano int4 not null,
  data_inicio date not null,
  data_fim date not null,
  dias int4 default 0 not null,
  notas text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.field_checkins (
  id text,
  promotora text,
  promotora_id uuid,
  loja text not null,
  rupturas bool default false,
  foto bool default false,
  notas text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.formacoes_catalogo (
  id text,
  nome text not null,
  area text,
  modalidade text,
  duracao_h numeric(6,1) default 0 not null,
  obrigatoria bool default false not null,
  estado text default 'Disponível'::text not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.formacoes_conclusoes (
  id text,
  colaborador text not null,
  formacao text not null,
  data date,
  horas numeric(6,1) default 0 not null,
  employee_id text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.fssc_items (
  id text,
  area text,
  requisito text,
  estado text default 'Pendente'::text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.inquerito_respostas (
  id uuid default gen_random_uuid(),
  token text,
  cliente_id text default ''::text not null,
  comercial text default '—'::text not null,
  respostas jsonb not null,
  nps int4,
  quer_contacto bool default false not null,
  criado_em timestamptz default now() not null,
  estabelecimento_id text,
  nome_respondente text default ''::text not null,
  telefone_respondente text default ''::text not null,
  email_respondente text default ''::text not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.medical_exams (
  id text,
  colaborador text,
  tipo text,
  ultimo date,
  proximo date,
  estado text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.metas (
  id text,
  ano int4 not null,
  mes int4 not null,
  dimensao text not null,
  chave text not null,
  valor numeric(16,2) default 0 not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.non_conformities (
  id text,
  titulo text not null,
  gravidade text not null,
  estado text default 'Aberta'::text not null,
  cliente text,
  lote text,
  produto text,
  departamento text,
  data date,
  criado_em timestamptz default now(),
  causa_raiz text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.objectives (
  id text,
  colaborador text not null,
  funcao text,
  ano int4 not null,
  kpi text not null,
  meta text,
  atual text,
  progresso numeric(5,4) default 0,
  peso numeric(5,4) default 0,
  employee_id text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.objetivos_comerciais (
  id text,
  dimensao text not null,
  nome text not null,
  objetivo numeric default 0 not null,
  real_a_data numeric default 0 not null,
  venda_dia numeric default 0 not null,
  ano int4,
  mes int4,
  snapshot_data date,
  dias_uteis int4,
  dias_ocorridos int4,
  dias_restantes int4,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.objetivos_comissao (
  id text,
  ano int4 not null,
  mes int4 not null,
  comercial text not null,
  marca text not null,
  valor numeric(16,2) default 0 not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.oportunidades (
  id text,
  nome text not null,
  contacto text,
  telefone text,
  email text,
  canal text,
  valor_estimado numeric default 0 not null,
  fase text default 'Novo'::text not null,
  responsavel text,
  proxima_acao text,
  data_prevista date,
  notas text,
  criado_em timestamptz default now() not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.order_linhas (
  id text,
  order_id text not null,
  ref text,
  produto text,
  quantidade numeric,
  faturado numeric,
  valor numeric,
  atualizado_em timestamptz default now() not null,
  picking numeric,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.orders (
  id text,
  cliente_id text,
  canal text not null,
  marca text,
  data date not null,
  estado text default 'Pendente'::text not null,
  valor numeric(16,2) default 0 not null,
  fill_rate numeric(5,4) default 1,
  itens int4 default 0,
  criado_por uuid,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.partilhas (
  codigo text not null,
  bucket text not null,
  caminho text not null,
  nome text default ''::text not null,
  criado_por text default ''::text not null,
  criado_em timestamptz default now(),
  expira_em timestamptz,
  ativo bool default true not null,
  acessos int4 default 0 not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (codigo)
);

create table if not exists produto.payroll_config (
  id text default 'default'::text,
  inss_trabalhador numeric(6,4) default 0.03 not null,
  inss_empresa numeric(6,4) default 0.08 not null,
  isencao_alimentacao numeric(16,2) default 30000 not null,
  isencao_transporte numeric(16,2) default 30000 not null,
  irt_escaloes jsonb not null,
  atualizado_em timestamptz default now() not null,
  abono_por_filho numeric default 0 not null,
  validado_por text,
  validado_em timestamptz,
  ponto_regras jsonb,
  outras_remuneracoes_inss bool default true not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.pdis (
  id text,
  colaborador text not null,
  objetivo text not null,
  accao text,
  prazo date,
  estado text default 'Planeado'::text not null,
  atualizado_em timestamptz default now() not null,
  employee_id text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.percursos (
  id text,
  nome text not null,
  publico text,
  modulos int4 default 0 not null,
  concluidos int4 default 0 not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.pickings_dia (
  id text,
  obrano int4,
  cliente_id text,
  nome text,
  data date not null,
  valor numeric(18,2) default 0 not null,
  itens int4 default 0 not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.ponto_correcoes (
  id uuid default gen_random_uuid(),
  employee_id text not null,
  ponto_id text,
  data date not null,
  entrada time,
  saida time,
  motivo text not null,
  observacoes text,
  autorizado_por text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.ponto_marcacoes (
  id text,
  ponto_id text not null,
  nome text,
  data date not null,
  primeira timestamptz,
  ultima timestamptz,
  total_marcacoes int4 default 0 not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.pontos_venda (
  id text,
  cliente_id text not null,
  nome text not null,
  morada text,
  cidade text,
  contacto_nome text,
  contacto_telefone text,
  horario_entrega text,
  ativo bool default true not null,
  notas text,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.processos_disciplinares (
  id text,
  colaborador text not null,
  tipo text not null,
  motivo text,
  data_abertura date,
  estado text default 'Em curso'::text not null,
  desfecho text,
  data_fecho date,
  criado_por uuid,
  criado_por_nome text,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.profiles (
  id uuid,
  nome text not null,
  email text not null,
  role text not null,
  nivel text default 'membro'::text not null,
  cargo text,
  ativo bool default true not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.radar_planos (
  id int8,
  semana date not null,
  comercial text default '—'::text not null,
  cliente_id text not null,
  cliente text default ''::text not null,
  tipo text not null,
  ref text,
  artigo text default ''::text not null,
  titulo text default ''::text not null,
  valor_mes numeric(18,2) default 0 not null,
  prioridade int4 default 2 not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.radar_respostas (
  id int8,
  semana date not null,
  comercial text not null,
  cliente_id text default ''::text not null,
  tipo text not null,
  ref text default ''::text not null,
  estado text,
  nota text,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.radar_tokens (
  comercial text not null,
  token text not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (comercial)
);

create table if not exists produto.recibo_envios (
  codigo text not null,
  colaborador_id text not null,
  colaborador_nome text default ''::text not null,
  ano int4 not null,
  mes int4 not null,
  dados jsonb default '{}'::jsonb not null,
  estado text default 'Enviado'::text not null,
  enviado_por text,
  enviado_em timestamptz default now(),
  confirmado_em timestamptz,
  nome_confirmacao text,
  assinatura_caminho text,
  ip text,
  user_agent text,
  motivo_contestacao text,
  expira_em timestamptz,
  empresa_id uuid not null references produto.empresas(id),
  primary key (codigo)
);

create table if not exists produto.recibos (
  id text,
  employee_id text,
  colaborador text,
  ano int4 not null,
  mes int4 not null,
  bruto numeric(16,2) default 0 not null,
  base_irt numeric(16,2) default 0 not null,
  inss numeric(16,2) default 0 not null,
  inss_empresa numeric(16,2) default 0 not null,
  irt numeric(16,2) default 0 not null,
  liquido numeric(16,2) default 0 not null,
  detalhe jsonb,
  criado_por uuid,
  criado_em timestamptz default now() not null,
  cambio_eur numeric,
  moeda text,
  periodo_inicio date,
  periodo_fim date,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.registos_interacao (
  id text,
  autor_id text not null,
  autor_nome text default ''::text not null,
  cliente_id text not null,
  cliente_nome text default ''::text not null,
  tipo text default 'Visita'::text not null,
  quando timestamptz default now() not null,
  notas text,
  resultado text,
  criado_em timestamptz default now(),
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.remuneracoes (
  employee_id text not null,
  salario_base numeric(16,2) default 0 not null,
  sub_alimentacao numeric(16,2) default 0 not null,
  sub_transporte numeric(16,2) default 0 not null,
  ajudas_custo numeric(16,2) default 0 not null,
  premio_assiduidade numeric(16,2) default 0 not null,
  recebe_ferias bool default true not null,
  recebe_natal bool default true not null,
  atualizado_em timestamptz default now() not null,
  desconta_ss bool default true not null,
  sub_habitacao numeric default 0 not null,
  moeda text default 'AKZ'::text not null,
  sub_alimentacao_dia numeric(12,2),
  sub_transporte_dia numeric(12,2),
  recebe_comissoes bool default true not null,
  sub_alimentacao_frequencia text default 'Mensal'::text not null,
  sub_alimentacao_valor_unitario numeric(12,2),
  sub_transporte_frequencia text default 'Mensal'::text not null,
  sub_transporte_valor_unitario numeric(12,2),
  tipo_salario text default 'Bruto'::text not null,
  salario_liquido_alvo numeric(12,2),
  outras_remuneracoes numeric(12,2) default 0 not null,
  outras_remuneracoes_descricao text,
  percentagem_ferias numeric(5,2) default 50 not null,
  percentagem_natal numeric(5,2) default 50 not null,
  sub_alimentacao_dias_manual int4,
  sub_transporte_dias_manual int4,
  empresa_id uuid not null references produto.empresas(id),
  primary key (employee_id)
);

create table if not exists produto.remuneracoes_categoria (
  categoria text not null,
  salario_base numeric(14,2) default 0 not null,
  subsidios jsonb default '[]'::jsonb not null,
  moeda text default 'AOA'::text not null,
  notas text,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (categoria)
);

create table if not exists produto.rota_promotora (
  id int8,
  semana date not null,
  promotora text not null,
  plano_id text not null,
  loja text default ''::text not null,
  cadeia text,
  cidade text,
  cliente_id text,
  dia int4 default 1 not null,
  ordem int4 default 0 not null,
  visitado bool default false not null,
  origem text default 'auto'::text not null,
  criado_em timestamptz default now() not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.rota_semana (
  id int8,
  semana date not null,
  comercial text not null,
  cliente_id text not null,
  nome text default ''::text not null,
  dia int4 default 1 not null,
  tipo text default 'visita'::text not null,
  zona text,
  prioridade numeric(18,2) default 0 not null,
  tem_cobranca bool default false not null,
  telefone text,
  acao text default ''::text not null,
  acao_tipo text,
  ordem int4 default 0 not null,
  visitado bool default false not null,
  nota text,
  origem text default 'auto'::text not null,
  criado_em timestamptz default now() not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.shopping_audits (
  id text,
  promotora text,
  promotora_id uuid,
  loja text not null,
  cadeia text,
  cidade text,
  canal text,
  itens jsonb default '[]'::jsonb not null,
  foto bool default false,
  notas text,
  data date default now() not null,
  criado_em timestamptz default now() not null,
  foto_url text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.skus (
  id text,
  descricao text not null,
  marca text,
  categoria text,
  stock int4 default 0,
  stock_minimo int4 default 0,
  preco_unit numeric(12,2) default 0,
  unidade text,
  shelf_life_dias int4,
  custo_medio numeric,
  custo_producao numeric(18,2),
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.slots_pessoal (
  id text,
  area text not null,
  categoria text not null,
  slots int4 default 0 not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.sst_incidents (
  id text,
  tipo text,
  area text,
  gravidade text,
  dias_baixa int4 default 0,
  estado text default 'Aberto'::text,
  data date,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.stock_armazem (
  id text,
  sku_id text,
  armazem int4 not null,
  stock numeric(14,3) default 0 not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.stock_lots (
  id text,
  sku_id text,
  marca text,
  quantidade int4 default 0,
  validade date,
  valor numeric(16,2) default 0,
  estado text default 'Ativo'::text not null,
  data_producao date,
  fornecedor text,
  lote_numero text,
  origem jsonb default '[]'::jsonb not null,
  armazem text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.tab_cl (
  cliente_id text not null,
  designacao text,
  comercial_num text,
  comercial text,
  segmento text,
  atualizado_em timestamptz default now() not null,
  canal text,
  regiao text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (cliente_id)
);

create table if not exists produto.tab_sku (
  ref text not null,
  designacao text,
  segmentacao text,
  marca text,
  subsegmentacao text,
  linha_produto text,
  tipo_produto text,
  origem text,
  unidade text,
  fc numeric,
  medida text,
  peso numeric,
  cod_pautal text,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (ref)
);

create table if not exists produto.tasks (
  id text,
  titulo text,
  descricao text,
  departamento text,
  responsavel text,
  estado text default 'Aberta'::text,
  prioridade text,
  prazo date,
  origem text,
  criado_em timestamptz default now(),
  criado_por uuid,
  criado_por_nome text,
  atualizado_em timestamptz,
  atualizado_por_nome text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.team_directory (
  email text not null,
  nome text not null,
  role text not null,
  nivel text not null,
  cargo text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (email)
);

create table if not exists produto.trainings (
  id text,
  nome text,
  obrigatoria bool default false,
  colaboradores_pendentes int4 default 0,
  validade date,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.turnos (
  id text,
  nome text not null,
  hora_inicio time,
  hora_fim time,
  dias_semana text,
  cor text,
  ativo bool default true not null,
  criado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.vehicles (
  id text,
  matricula text,
  tipo text,
  motorista text,
  estado_manutencao text,
  proxima_inspecao date,
  seguradora text,
  apolice_seguro text,
  validade_seguro date,
  ativo bool default true not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.vendas_linhas (
  id text,
  documento text,
  tipo_doc text,
  cliente_id text,
  comercial text,
  data date,
  ano int4,
  mes int4,
  segmento text,
  ref text,
  artigo text,
  marca text,
  quantidade numeric(16,3) default 0 not null,
  valor numeric(18,2) default 0 not null,
  custo numeric(18,2) default 0 not null,
  margem numeric(18,2) default 0 not null,
  atualizado_em timestamptz default now() not null,
  lote text,
  ftstamp text,
  encomenda_id text,
  encomenda_num text,
  encomenda_data date,
  picking_id text,
  picking_data date,
  estab int4,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.visita_registos (
  id int8,
  data date default CURRENT_DATE not null,
  autor_id text not null,
  autor text not null,
  papel text default 'promotora'::text not null,
  loja text,
  cliente_id text,
  cliente text,
  rota_id int8,
  entrada timestamptz default now() not null,
  saida timestamptz,
  itens jsonb default '[]'::jsonb not null,
  fotos jsonb default '[]'::jsonb not null,
  notas text,
  oportunidades text,
  dificuldades text,
  estado text default 'aberta'::text not null,
  criado_em timestamptz default now() not null,
  atualizado_em timestamptz default now() not null,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);

create table if not exists produto.visitas_plano (
  id text,
  promotora text not null,
  loja text not null,
  cadeia text,
  cidade text,
  canal text,
  frequencia int4 default 7 not null,
  ativo bool default true not null,
  atualizado_em timestamptz default now() not null,
  cliente_id text,
  empresa_id uuid not null references produto.empresas(id),
  primary key (id)
);


-- Índice por empresa em cada tabela — toda a consulta operacional vai
-- filtrar por aqui.


create index if not exists account_movements_empresa_id_idx on produto.account_movements (empresa_id);

create index if not exists acoes_comerciais_empresa_id_idx on produto.acoes_comerciais (empresa_id);

create index if not exists agenda_comercial_empresa_id_idx on produto.agenda_comercial (empresa_id);

create index if not exists alertas_estado_empresa_id_idx on produto.alertas_estado (empresa_id);

create index if not exists audit_log_empresa_id_idx on produto.audit_log (empresa_id);

create index if not exists ausencias_empresa_id_idx on produto.ausencias (empresa_id);

create index if not exists cambio_salarios_empresa_id_idx on produto.cambio_salarios (empresa_id);

create index if not exists cobrancas_empresa_id_idx on produto.cobrancas (empresa_id);

create index if not exists colaborador_amortizacoes_empresa_id_idx on produto.colaborador_amortizacoes (empresa_id);

create index if not exists colaborador_avaliacoes_internas_empresa_id_idx on produto.colaborador_avaliacoes_internas (empresa_id);

create index if not exists colaborador_dividas_empresa_id_idx on produto.colaborador_dividas (empresa_id);

create index if not exists colaborador_documentos_empresa_id_idx on produto.colaborador_documentos (empresa_id);

create index if not exists comissao_config_empresa_id_idx on produto.comissao_config (empresa_id);

create index if not exists competencias_empresa_id_idx on produto.competencias (empresa_id);

create index if not exists complaints_empresa_id_idx on produto.complaints (empresa_id);

create index if not exists contactos_empresa_id_idx on produto.contactos (empresa_id);

create index if not exists contratos_trabalho_empresa_id_idx on produto.contratos_trabalho (empresa_id);

create index if not exists corrective_actions_empresa_id_idx on produto.corrective_actions (empresa_id);

create index if not exists customers_empresa_id_idx on produto.customers (empresa_id);

create index if not exists devolucoes_empresa_id_idx on produto.devolucoes (empresa_id);

create index if not exists disc_resultados_empresa_id_idx on produto.disc_resultados (empresa_id);

create index if not exists documentos_cliente_empresa_id_idx on produto.documentos_cliente (empresa_id);

create index if not exists documentos_fatura_empresa_id_idx on produto.documentos_fatura (empresa_id);

create index if not exists documentos_por_atribuir_empresa_id_idx on produto.documentos_por_atribuir (empresa_id);

create index if not exists drivers_empresa_id_idx on produto.drivers (empresa_id);

create index if not exists employees_empresa_id_idx on produto.employees (empresa_id);

create index if not exists encomendas_dia_empresa_id_idx on produto.encomendas_dia (empresa_id);

create index if not exists entregas_empresa_id_idx on produto.entregas (empresa_id);

create index if not exists epi_items_empresa_id_idx on produto.epi_items (empresa_id);

create index if not exists estabelecimentos_empresa_id_idx on produto.estabelecimentos (empresa_id);

create index if not exists extrato_partilhas_empresa_id_idx on produto.extrato_partilhas (empresa_id);

create index if not exists feriados_empresa_id_idx on produto.feriados (empresa_id);

create index if not exists ferias_empresa_id_idx on produto.ferias (empresa_id);

create index if not exists ferias_periodos_empresa_id_idx on produto.ferias_periodos (empresa_id);

create index if not exists field_checkins_empresa_id_idx on produto.field_checkins (empresa_id);

create index if not exists formacoes_catalogo_empresa_id_idx on produto.formacoes_catalogo (empresa_id);

create index if not exists formacoes_conclusoes_empresa_id_idx on produto.formacoes_conclusoes (empresa_id);

create index if not exists fssc_items_empresa_id_idx on produto.fssc_items (empresa_id);

create index if not exists inquerito_respostas_empresa_id_idx on produto.inquerito_respostas (empresa_id);

create index if not exists medical_exams_empresa_id_idx on produto.medical_exams (empresa_id);

create index if not exists metas_empresa_id_idx on produto.metas (empresa_id);

create index if not exists non_conformities_empresa_id_idx on produto.non_conformities (empresa_id);

create index if not exists objectives_empresa_id_idx on produto.objectives (empresa_id);

create index if not exists objetivos_comerciais_empresa_id_idx on produto.objetivos_comerciais (empresa_id);

create index if not exists objetivos_comissao_empresa_id_idx on produto.objetivos_comissao (empresa_id);

create index if not exists oportunidades_empresa_id_idx on produto.oportunidades (empresa_id);

create index if not exists order_linhas_empresa_id_idx on produto.order_linhas (empresa_id);

create index if not exists orders_empresa_id_idx on produto.orders (empresa_id);

create index if not exists partilhas_empresa_id_idx on produto.partilhas (empresa_id);

create index if not exists payroll_config_empresa_id_idx on produto.payroll_config (empresa_id);

create index if not exists pdis_empresa_id_idx on produto.pdis (empresa_id);

create index if not exists percursos_empresa_id_idx on produto.percursos (empresa_id);

create index if not exists pickings_dia_empresa_id_idx on produto.pickings_dia (empresa_id);

create index if not exists ponto_correcoes_empresa_id_idx on produto.ponto_correcoes (empresa_id);

create index if not exists ponto_marcacoes_empresa_id_idx on produto.ponto_marcacoes (empresa_id);

create index if not exists pontos_venda_empresa_id_idx on produto.pontos_venda (empresa_id);

create index if not exists processos_disciplinares_empresa_id_idx on produto.processos_disciplinares (empresa_id);

create index if not exists profiles_empresa_id_idx on produto.profiles (empresa_id);

create index if not exists radar_planos_empresa_id_idx on produto.radar_planos (empresa_id);

create index if not exists radar_respostas_empresa_id_idx on produto.radar_respostas (empresa_id);

create index if not exists radar_tokens_empresa_id_idx on produto.radar_tokens (empresa_id);

create index if not exists recibo_envios_empresa_id_idx on produto.recibo_envios (empresa_id);

create index if not exists recibos_empresa_id_idx on produto.recibos (empresa_id);

create index if not exists registos_interacao_empresa_id_idx on produto.registos_interacao (empresa_id);

create index if not exists remuneracoes_empresa_id_idx on produto.remuneracoes (empresa_id);

create index if not exists remuneracoes_categoria_empresa_id_idx on produto.remuneracoes_categoria (empresa_id);

create index if not exists rota_promotora_empresa_id_idx on produto.rota_promotora (empresa_id);

create index if not exists rota_semana_empresa_id_idx on produto.rota_semana (empresa_id);

create index if not exists shopping_audits_empresa_id_idx on produto.shopping_audits (empresa_id);

create index if not exists skus_empresa_id_idx on produto.skus (empresa_id);

create index if not exists slots_pessoal_empresa_id_idx on produto.slots_pessoal (empresa_id);

create index if not exists sst_incidents_empresa_id_idx on produto.sst_incidents (empresa_id);

create index if not exists stock_armazem_empresa_id_idx on produto.stock_armazem (empresa_id);

create index if not exists stock_lots_empresa_id_idx on produto.stock_lots (empresa_id);

create index if not exists tab_cl_empresa_id_idx on produto.tab_cl (empresa_id);

create index if not exists tab_sku_empresa_id_idx on produto.tab_sku (empresa_id);

create index if not exists tasks_empresa_id_idx on produto.tasks (empresa_id);

create index if not exists team_directory_empresa_id_idx on produto.team_directory (empresa_id);

create index if not exists trainings_empresa_id_idx on produto.trainings (empresa_id);

create index if not exists turnos_empresa_id_idx on produto.turnos (empresa_id);

create index if not exists vehicles_empresa_id_idx on produto.vehicles (empresa_id);

create index if not exists vendas_linhas_empresa_id_idx on produto.vendas_linhas (empresa_id);

create index if not exists visita_registos_empresa_id_idx on produto.visita_registos (empresa_id);

create index if not exists visitas_plano_empresa_id_idx on produto.visitas_plano (empresa_id);


-- RLS a sério, não só a bandeira ligada: cada tabela só devolve linhas
-- da empresa da sessão. app.empresa_id é definido pela app a cada
-- pedido (set_config), como segunda camada — para que um erro no
-- código de aplicação não seja a única coisa entre uma empresa e os
-- dados de outra.


alter table produto.account_movements enable row level security;
drop policy if exists account_movements_isolamento_empresa on produto.account_movements;
create policy account_movements_isolamento_empresa on produto.account_movements
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.acoes_comerciais enable row level security;
drop policy if exists acoes_comerciais_isolamento_empresa on produto.acoes_comerciais;
create policy acoes_comerciais_isolamento_empresa on produto.acoes_comerciais
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.agenda_comercial enable row level security;
drop policy if exists agenda_comercial_isolamento_empresa on produto.agenda_comercial;
create policy agenda_comercial_isolamento_empresa on produto.agenda_comercial
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.alertas_estado enable row level security;
drop policy if exists alertas_estado_isolamento_empresa on produto.alertas_estado;
create policy alertas_estado_isolamento_empresa on produto.alertas_estado
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.audit_log enable row level security;
drop policy if exists audit_log_isolamento_empresa on produto.audit_log;
create policy audit_log_isolamento_empresa on produto.audit_log
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.ausencias enable row level security;
drop policy if exists ausencias_isolamento_empresa on produto.ausencias;
create policy ausencias_isolamento_empresa on produto.ausencias
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.cambio_salarios enable row level security;
drop policy if exists cambio_salarios_isolamento_empresa on produto.cambio_salarios;
create policy cambio_salarios_isolamento_empresa on produto.cambio_salarios
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.cobrancas enable row level security;
drop policy if exists cobrancas_isolamento_empresa on produto.cobrancas;
create policy cobrancas_isolamento_empresa on produto.cobrancas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.colaborador_amortizacoes enable row level security;
drop policy if exists colaborador_amortizacoes_isolamento_empresa on produto.colaborador_amortizacoes;
create policy colaborador_amortizacoes_isolamento_empresa on produto.colaborador_amortizacoes
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.colaborador_avaliacoes_internas enable row level security;
drop policy if exists colaborador_avaliacoes_internas_isolamento_empresa on produto.colaborador_avaliacoes_internas;
create policy colaborador_avaliacoes_internas_isolamento_empresa on produto.colaborador_avaliacoes_internas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.colaborador_dividas enable row level security;
drop policy if exists colaborador_dividas_isolamento_empresa on produto.colaborador_dividas;
create policy colaborador_dividas_isolamento_empresa on produto.colaborador_dividas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.colaborador_documentos enable row level security;
drop policy if exists colaborador_documentos_isolamento_empresa on produto.colaborador_documentos;
create policy colaborador_documentos_isolamento_empresa on produto.colaborador_documentos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.comissao_config enable row level security;
drop policy if exists comissao_config_isolamento_empresa on produto.comissao_config;
create policy comissao_config_isolamento_empresa on produto.comissao_config
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.competencias enable row level security;
drop policy if exists competencias_isolamento_empresa on produto.competencias;
create policy competencias_isolamento_empresa on produto.competencias
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.complaints enable row level security;
drop policy if exists complaints_isolamento_empresa on produto.complaints;
create policy complaints_isolamento_empresa on produto.complaints
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.contactos enable row level security;
drop policy if exists contactos_isolamento_empresa on produto.contactos;
create policy contactos_isolamento_empresa on produto.contactos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.contratos_trabalho enable row level security;
drop policy if exists contratos_trabalho_isolamento_empresa on produto.contratos_trabalho;
create policy contratos_trabalho_isolamento_empresa on produto.contratos_trabalho
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.corrective_actions enable row level security;
drop policy if exists corrective_actions_isolamento_empresa on produto.corrective_actions;
create policy corrective_actions_isolamento_empresa on produto.corrective_actions
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.customers enable row level security;
drop policy if exists customers_isolamento_empresa on produto.customers;
create policy customers_isolamento_empresa on produto.customers
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.devolucoes enable row level security;
drop policy if exists devolucoes_isolamento_empresa on produto.devolucoes;
create policy devolucoes_isolamento_empresa on produto.devolucoes
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.disc_resultados enable row level security;
drop policy if exists disc_resultados_isolamento_empresa on produto.disc_resultados;
create policy disc_resultados_isolamento_empresa on produto.disc_resultados
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.documentos_cliente enable row level security;
drop policy if exists documentos_cliente_isolamento_empresa on produto.documentos_cliente;
create policy documentos_cliente_isolamento_empresa on produto.documentos_cliente
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.documentos_fatura enable row level security;
drop policy if exists documentos_fatura_isolamento_empresa on produto.documentos_fatura;
create policy documentos_fatura_isolamento_empresa on produto.documentos_fatura
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.documentos_por_atribuir enable row level security;
drop policy if exists documentos_por_atribuir_isolamento_empresa on produto.documentos_por_atribuir;
create policy documentos_por_atribuir_isolamento_empresa on produto.documentos_por_atribuir
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.drivers enable row level security;
drop policy if exists drivers_isolamento_empresa on produto.drivers;
create policy drivers_isolamento_empresa on produto.drivers
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.employees enable row level security;
drop policy if exists employees_isolamento_empresa on produto.employees;
create policy employees_isolamento_empresa on produto.employees
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.encomendas_dia enable row level security;
drop policy if exists encomendas_dia_isolamento_empresa on produto.encomendas_dia;
create policy encomendas_dia_isolamento_empresa on produto.encomendas_dia
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.entregas enable row level security;
drop policy if exists entregas_isolamento_empresa on produto.entregas;
create policy entregas_isolamento_empresa on produto.entregas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.epi_items enable row level security;
drop policy if exists epi_items_isolamento_empresa on produto.epi_items;
create policy epi_items_isolamento_empresa on produto.epi_items
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.estabelecimentos enable row level security;
drop policy if exists estabelecimentos_isolamento_empresa on produto.estabelecimentos;
create policy estabelecimentos_isolamento_empresa on produto.estabelecimentos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.extrato_partilhas enable row level security;
drop policy if exists extrato_partilhas_isolamento_empresa on produto.extrato_partilhas;
create policy extrato_partilhas_isolamento_empresa on produto.extrato_partilhas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.feriados enable row level security;
drop policy if exists feriados_isolamento_empresa on produto.feriados;
create policy feriados_isolamento_empresa on produto.feriados
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.ferias enable row level security;
drop policy if exists ferias_isolamento_empresa on produto.ferias;
create policy ferias_isolamento_empresa on produto.ferias
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.ferias_periodos enable row level security;
drop policy if exists ferias_periodos_isolamento_empresa on produto.ferias_periodos;
create policy ferias_periodos_isolamento_empresa on produto.ferias_periodos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.field_checkins enable row level security;
drop policy if exists field_checkins_isolamento_empresa on produto.field_checkins;
create policy field_checkins_isolamento_empresa on produto.field_checkins
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.formacoes_catalogo enable row level security;
drop policy if exists formacoes_catalogo_isolamento_empresa on produto.formacoes_catalogo;
create policy formacoes_catalogo_isolamento_empresa on produto.formacoes_catalogo
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.formacoes_conclusoes enable row level security;
drop policy if exists formacoes_conclusoes_isolamento_empresa on produto.formacoes_conclusoes;
create policy formacoes_conclusoes_isolamento_empresa on produto.formacoes_conclusoes
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.fssc_items enable row level security;
drop policy if exists fssc_items_isolamento_empresa on produto.fssc_items;
create policy fssc_items_isolamento_empresa on produto.fssc_items
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.inquerito_respostas enable row level security;
drop policy if exists inquerito_respostas_isolamento_empresa on produto.inquerito_respostas;
create policy inquerito_respostas_isolamento_empresa on produto.inquerito_respostas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.medical_exams enable row level security;
drop policy if exists medical_exams_isolamento_empresa on produto.medical_exams;
create policy medical_exams_isolamento_empresa on produto.medical_exams
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.metas enable row level security;
drop policy if exists metas_isolamento_empresa on produto.metas;
create policy metas_isolamento_empresa on produto.metas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.non_conformities enable row level security;
drop policy if exists non_conformities_isolamento_empresa on produto.non_conformities;
create policy non_conformities_isolamento_empresa on produto.non_conformities
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.objectives enable row level security;
drop policy if exists objectives_isolamento_empresa on produto.objectives;
create policy objectives_isolamento_empresa on produto.objectives
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.objetivos_comerciais enable row level security;
drop policy if exists objetivos_comerciais_isolamento_empresa on produto.objetivos_comerciais;
create policy objetivos_comerciais_isolamento_empresa on produto.objetivos_comerciais
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.objetivos_comissao enable row level security;
drop policy if exists objetivos_comissao_isolamento_empresa on produto.objetivos_comissao;
create policy objetivos_comissao_isolamento_empresa on produto.objetivos_comissao
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.oportunidades enable row level security;
drop policy if exists oportunidades_isolamento_empresa on produto.oportunidades;
create policy oportunidades_isolamento_empresa on produto.oportunidades
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.order_linhas enable row level security;
drop policy if exists order_linhas_isolamento_empresa on produto.order_linhas;
create policy order_linhas_isolamento_empresa on produto.order_linhas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.orders enable row level security;
drop policy if exists orders_isolamento_empresa on produto.orders;
create policy orders_isolamento_empresa on produto.orders
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.partilhas enable row level security;
drop policy if exists partilhas_isolamento_empresa on produto.partilhas;
create policy partilhas_isolamento_empresa on produto.partilhas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.payroll_config enable row level security;
drop policy if exists payroll_config_isolamento_empresa on produto.payroll_config;
create policy payroll_config_isolamento_empresa on produto.payroll_config
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.pdis enable row level security;
drop policy if exists pdis_isolamento_empresa on produto.pdis;
create policy pdis_isolamento_empresa on produto.pdis
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.percursos enable row level security;
drop policy if exists percursos_isolamento_empresa on produto.percursos;
create policy percursos_isolamento_empresa on produto.percursos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.pickings_dia enable row level security;
drop policy if exists pickings_dia_isolamento_empresa on produto.pickings_dia;
create policy pickings_dia_isolamento_empresa on produto.pickings_dia
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.ponto_correcoes enable row level security;
drop policy if exists ponto_correcoes_isolamento_empresa on produto.ponto_correcoes;
create policy ponto_correcoes_isolamento_empresa on produto.ponto_correcoes
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.ponto_marcacoes enable row level security;
drop policy if exists ponto_marcacoes_isolamento_empresa on produto.ponto_marcacoes;
create policy ponto_marcacoes_isolamento_empresa on produto.ponto_marcacoes
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.pontos_venda enable row level security;
drop policy if exists pontos_venda_isolamento_empresa on produto.pontos_venda;
create policy pontos_venda_isolamento_empresa on produto.pontos_venda
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.processos_disciplinares enable row level security;
drop policy if exists processos_disciplinares_isolamento_empresa on produto.processos_disciplinares;
create policy processos_disciplinares_isolamento_empresa on produto.processos_disciplinares
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.profiles enable row level security;
drop policy if exists profiles_isolamento_empresa on produto.profiles;
create policy profiles_isolamento_empresa on produto.profiles
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.radar_planos enable row level security;
drop policy if exists radar_planos_isolamento_empresa on produto.radar_planos;
create policy radar_planos_isolamento_empresa on produto.radar_planos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.radar_respostas enable row level security;
drop policy if exists radar_respostas_isolamento_empresa on produto.radar_respostas;
create policy radar_respostas_isolamento_empresa on produto.radar_respostas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.radar_tokens enable row level security;
drop policy if exists radar_tokens_isolamento_empresa on produto.radar_tokens;
create policy radar_tokens_isolamento_empresa on produto.radar_tokens
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.recibo_envios enable row level security;
drop policy if exists recibo_envios_isolamento_empresa on produto.recibo_envios;
create policy recibo_envios_isolamento_empresa on produto.recibo_envios
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.recibos enable row level security;
drop policy if exists recibos_isolamento_empresa on produto.recibos;
create policy recibos_isolamento_empresa on produto.recibos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.registos_interacao enable row level security;
drop policy if exists registos_interacao_isolamento_empresa on produto.registos_interacao;
create policy registos_interacao_isolamento_empresa on produto.registos_interacao
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.remuneracoes enable row level security;
drop policy if exists remuneracoes_isolamento_empresa on produto.remuneracoes;
create policy remuneracoes_isolamento_empresa on produto.remuneracoes
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.remuneracoes_categoria enable row level security;
drop policy if exists remuneracoes_categoria_isolamento_empresa on produto.remuneracoes_categoria;
create policy remuneracoes_categoria_isolamento_empresa on produto.remuneracoes_categoria
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.rota_promotora enable row level security;
drop policy if exists rota_promotora_isolamento_empresa on produto.rota_promotora;
create policy rota_promotora_isolamento_empresa on produto.rota_promotora
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.rota_semana enable row level security;
drop policy if exists rota_semana_isolamento_empresa on produto.rota_semana;
create policy rota_semana_isolamento_empresa on produto.rota_semana
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.shopping_audits enable row level security;
drop policy if exists shopping_audits_isolamento_empresa on produto.shopping_audits;
create policy shopping_audits_isolamento_empresa on produto.shopping_audits
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.skus enable row level security;
drop policy if exists skus_isolamento_empresa on produto.skus;
create policy skus_isolamento_empresa on produto.skus
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.slots_pessoal enable row level security;
drop policy if exists slots_pessoal_isolamento_empresa on produto.slots_pessoal;
create policy slots_pessoal_isolamento_empresa on produto.slots_pessoal
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.sst_incidents enable row level security;
drop policy if exists sst_incidents_isolamento_empresa on produto.sst_incidents;
create policy sst_incidents_isolamento_empresa on produto.sst_incidents
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.stock_armazem enable row level security;
drop policy if exists stock_armazem_isolamento_empresa on produto.stock_armazem;
create policy stock_armazem_isolamento_empresa on produto.stock_armazem
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.stock_lots enable row level security;
drop policy if exists stock_lots_isolamento_empresa on produto.stock_lots;
create policy stock_lots_isolamento_empresa on produto.stock_lots
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.tab_cl enable row level security;
drop policy if exists tab_cl_isolamento_empresa on produto.tab_cl;
create policy tab_cl_isolamento_empresa on produto.tab_cl
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.tab_sku enable row level security;
drop policy if exists tab_sku_isolamento_empresa on produto.tab_sku;
create policy tab_sku_isolamento_empresa on produto.tab_sku
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.tasks enable row level security;
drop policy if exists tasks_isolamento_empresa on produto.tasks;
create policy tasks_isolamento_empresa on produto.tasks
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.team_directory enable row level security;
drop policy if exists team_directory_isolamento_empresa on produto.team_directory;
create policy team_directory_isolamento_empresa on produto.team_directory
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.trainings enable row level security;
drop policy if exists trainings_isolamento_empresa on produto.trainings;
create policy trainings_isolamento_empresa on produto.trainings
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.turnos enable row level security;
drop policy if exists turnos_isolamento_empresa on produto.turnos;
create policy turnos_isolamento_empresa on produto.turnos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.vehicles enable row level security;
drop policy if exists vehicles_isolamento_empresa on produto.vehicles;
create policy vehicles_isolamento_empresa on produto.vehicles
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.vendas_linhas enable row level security;
drop policy if exists vendas_linhas_isolamento_empresa on produto.vendas_linhas;
create policy vendas_linhas_isolamento_empresa on produto.vendas_linhas
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.visita_registos enable row level security;
drop policy if exists visita_registos_isolamento_empresa on produto.visita_registos;
create policy visita_registos_isolamento_empresa on produto.visita_registos
  using (empresa_id::text = current_setting('app.empresa_id', true));

alter table produto.visitas_plano enable row level security;
drop policy if exists visitas_plano_isolamento_empresa on produto.visitas_plano;
create policy visitas_plano_isolamento_empresa on produto.visitas_plano
  using (empresa_id::text = current_setting('app.empresa_id', true));
